# Włącz (enabled = true), jeśli panel jest dostępny spoza sieci lokalnej
[smsgui]
enabled  = false
port     = http,https
filter   = smsgui
logpath  = /var/lib/smsgui/smsgui.log
maxretry = 5
findtime = 15m
bantime  = 1h
