# Nieudane logowania do Gammu SMSD Web UI (wpis w /var/lib/smsgui/smsgui.log)
# 2026-10-04 11:42:10 smsgui[auth]: failed login for user "admin" from 192.168.1.20
[Definition]
failregex = smsgui\[auth\]: failed login for user ".*" from <HOST>$
ignoreregex =
